/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerifyCertNumberRouteImport } from './routes/verify.$certNumber'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentPaymentsRouteImport } from './routes/student.payments'
import { Route as StudentCertificatesRouteImport } from './routes/student.certificates'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentAnnouncementsRouteImport } from './routes/student.announcements'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminViolationsRouteImport } from './routes/admin.violations'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSchedulerRouteImport } from './routes/admin.scheduler'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminQuestionBankRouteImport } from './routes/admin.question-bank'
import { Route as AdminOrganizationRouteImport } from './routes/admin.organization'
import { Route as AdminLiveMonitorRouteImport } from './routes/admin.live-monitor'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminCommunicationRouteImport } from './routes/admin.communication'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAcademicIntegrityRouteImport } from './routes/admin.academic-integrity'
import { Route as ApiResultsExportRouteImport } from './routes/api/results.export'
import { Route as ApiCertificatesVerifyRouteImport } from './routes/api/certificates.verify'
import { Route as ApiAttendanceQrRouteImport } from './routes/api/attendance.qr'
import { Route as StudentExamsIdSessionRouteImport } from './routes/student.exams.$id.session'
import { Route as StudentExamsIdCheckinRouteImport } from './routes/student.exams.$id.checkin'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AdminExamsExamIdBuilderRouteImport } from './routes/admin.exams.$examId.builder'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyCertNumberRoute = VerifyCertNumberRouteImport.update({
  id: '/verify/$certNumber',
  path: '/verify/$certNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPaymentsRoute = StudentPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAnnouncementsRoute = StudentAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => StudentRoute,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViolationsRoute = AdminViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulerRoute = AdminSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionBankRoute = AdminQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveMonitorRoute = AdminLiveMonitorRouteImport.update({
  id: '/live-monitor',
  path: '/live-monitor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationRoute = AdminCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicIntegrityRoute = AdminAcademicIntegrityRouteImport.update({
  id: '/academic-integrity',
  path: '/academic-integrity',
  getParentRoute: () => AdminRoute,
} as any)
const ApiResultsExportRoute = ApiResultsExportRouteImport.update({
  id: '/api/results/export',
  path: '/api/results/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCertificatesVerifyRoute = ApiCertificatesVerifyRouteImport.update({
  id: '/api/certificates/verify',
  path: '/api/certificates/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceQrRoute = ApiAttendanceQrRouteImport.update({
  id: '/api/attendance/qr',
  path: '/api/attendance/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentExamsIdSessionRoute = StudentExamsIdSessionRouteImport.update({
  id: '/exams/$id/session',
  path: '/exams/$id/session',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamsIdCheckinRoute = StudentExamsIdCheckinRouteImport.update({
  id: '/exams/$id/checkin',
  path: '/exams/$id/checkin',
  getParentRoute: () => StudentRoute,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamsExamIdBuilderRoute = AdminExamsExamIdBuilderRouteImport.update({
  id: '/$examId/builder',
  path: '/$examId/builder',
  getParentRoute: () => AdminExamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/not-found': typeof NotFoundRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/academic-integrity': typeof AdminAcademicIntegrityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/live-monitor': typeof AdminLiveMonitorRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/scheduler': typeof AdminSchedulerRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/violations': typeof AdminViolationsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/student/announcements': typeof StudentAnnouncementsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/payments': typeof StudentPaymentsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/verify/$certNumber': typeof VerifyCertNumberRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/api/attendance/qr': typeof ApiAttendanceQrRoute
  '/api/certificates/verify': typeof ApiCertificatesVerifyRoute
  '/api/results/export': typeof ApiResultsExportRoute
  '/admin/exams/$examId/builder': typeof AdminExamsExamIdBuilderRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/student/exams/$id/checkin': typeof StudentExamsIdCheckinRoute
  '/student/exams/$id/session': typeof StudentExamsIdSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/not-found': typeof NotFoundRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/admin/academic-integrity': typeof AdminAcademicIntegrityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/live-monitor': typeof AdminLiveMonitorRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/scheduler': typeof AdminSchedulerRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/violations': typeof AdminViolationsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/student/announcements': typeof StudentAnnouncementsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/payments': typeof StudentPaymentsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/verify/$certNumber': typeof VerifyCertNumberRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/api/attendance/qr': typeof ApiAttendanceQrRoute
  '/api/certificates/verify': typeof ApiCertificatesVerifyRoute
  '/api/results/export': typeof ApiResultsExportRoute
  '/admin/exams/$examId/builder': typeof AdminExamsExamIdBuilderRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/student/exams/$id/checkin': typeof StudentExamsIdCheckinRoute
  '/student/exams/$id/session': typeof StudentExamsIdSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/not-found': typeof NotFoundRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/academic-integrity': typeof AdminAcademicIntegrityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/live-monitor': typeof AdminLiveMonitorRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/scheduler': typeof AdminSchedulerRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/violations': typeof AdminViolationsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/student/announcements': typeof StudentAnnouncementsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/payments': typeof StudentPaymentsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/verify/$certNumber': typeof VerifyCertNumberRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/api/attendance/qr': typeof ApiAttendanceQrRoute
  '/api/certificates/verify': typeof ApiCertificatesVerifyRoute
  '/api/results/export': typeof ApiResultsExportRoute
  '/admin/exams/$examId/builder': typeof AdminExamsExamIdBuilderRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/student/exams/$id/checkin': typeof StudentExamsIdCheckinRoute
  '/student/exams/$id/session': typeof StudentExamsIdSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/auth-callback'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/home'
    | '/not-found'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/solutions'
    | '/student'
    | '/admin/academic-integrity'
    | '/admin/analytics'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/billing'
    | '/admin/candidates'
    | '/admin/certificates'
    | '/admin/communication'
    | '/admin/exams'
    | '/admin/live-monitor'
    | '/admin/organization'
    | '/admin/question-bank'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/scheduler'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/team'
    | '/admin/violations'
    | '/api/health'
    | '/api/version'
    | '/student/announcements'
    | '/student/attendance'
    | '/student/certificates'
    | '/student/payments'
    | '/student/profile'
    | '/student/results'
    | '/verify/$certNumber'
    | '/admin/'
    | '/student/'
    | '/api/attendance/qr'
    | '/api/certificates/verify'
    | '/api/results/export'
    | '/admin/exams/$examId/builder'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/student/exams/$id/checkin'
    | '/student/exams/$id/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/auth-callback'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/home'
    | '/not-found'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/solutions'
    | '/admin/academic-integrity'
    | '/admin/analytics'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/billing'
    | '/admin/candidates'
    | '/admin/certificates'
    | '/admin/communication'
    | '/admin/exams'
    | '/admin/live-monitor'
    | '/admin/organization'
    | '/admin/question-bank'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/scheduler'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/team'
    | '/admin/violations'
    | '/api/health'
    | '/api/version'
    | '/student/announcements'
    | '/student/attendance'
    | '/student/certificates'
    | '/student/payments'
    | '/student/profile'
    | '/student/results'
    | '/verify/$certNumber'
    | '/admin'
    | '/student'
    | '/api/attendance/qr'
    | '/api/certificates/verify'
    | '/api/results/export'
    | '/admin/exams/$examId/builder'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/student/exams/$id/checkin'
    | '/student/exams/$id/session'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/auth-callback'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/home'
    | '/not-found'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/solutions'
    | '/student'
    | '/admin/academic-integrity'
    | '/admin/analytics'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/billing'
    | '/admin/candidates'
    | '/admin/certificates'
    | '/admin/communication'
    | '/admin/exams'
    | '/admin/live-monitor'
    | '/admin/organization'
    | '/admin/question-bank'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/scheduler'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/team'
    | '/admin/violations'
    | '/api/health'
    | '/api/version'
    | '/student/announcements'
    | '/student/attendance'
    | '/student/certificates'
    | '/student/payments'
    | '/student/profile'
    | '/student/results'
    | '/verify/$certNumber'
    | '/admin/'
    | '/student/'
    | '/api/attendance/qr'
    | '/api/certificates/verify'
    | '/api/results/export'
    | '/admin/exams/$examId/builder'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/student/exams/$id/checkin'
    | '/student/exams/$id/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  NotFoundRoute: typeof NotFoundRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
  StudentRoute: typeof StudentRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiVersionRoute: typeof ApiVersionRoute
  VerifyCertNumberRoute: typeof VerifyCertNumberRoute
  ApiAttendanceQrRoute: typeof ApiAttendanceQrRoute
  ApiCertificatesVerifyRoute: typeof ApiCertificatesVerifyRoute
  ApiResultsExportRoute: typeof ApiResultsExportRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/$certNumber': {
      id: '/verify/$certNumber'
      path: '/verify/$certNumber'
      fullPath: '/verify/$certNumber'
      preLoaderRoute: typeof VerifyCertNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/results': {
      id: '/student/results'
      path: '/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/payments': {
      id: '/student/payments'
      path: '/payments'
      fullPath: '/student/payments'
      preLoaderRoute: typeof StudentPaymentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/announcements': {
      id: '/student/announcements'
      path: '/announcements'
      fullPath: '/student/announcements'
      preLoaderRoute: typeof StudentAnnouncementsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/violations': {
      id: '/admin/violations'
      path: '/violations'
      fullPath: '/admin/violations'
      preLoaderRoute: typeof AdminViolationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scheduler': {
      id: '/admin/scheduler'
      path: '/scheduler'
      fullPath: '/admin/scheduler'
      preLoaderRoute: typeof AdminSchedulerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/question-bank': {
      id: '/admin/question-bank'
      path: '/question-bank'
      fullPath: '/admin/question-bank'
      preLoaderRoute: typeof AdminQuestionBankRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-monitor': {
      id: '/admin/live-monitor'
      path: '/live-monitor'
      fullPath: '/admin/live-monitor'
      preLoaderRoute: typeof AdminLiveMonitorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communication': {
      id: '/admin/communication'
      path: '/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AdminCommunicationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academic-integrity': {
      id: '/admin/academic-integrity'
      path: '/academic-integrity'
      fullPath: '/admin/academic-integrity'
      preLoaderRoute: typeof AdminAcademicIntegrityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/results/export': {
      id: '/api/results/export'
      path: '/api/results/export'
      fullPath: '/api/results/export'
      preLoaderRoute: typeof ApiResultsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificates/verify': {
      id: '/api/certificates/verify'
      path: '/api/certificates/verify'
      fullPath: '/api/certificates/verify'
      preLoaderRoute: typeof ApiCertificatesVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/qr': {
      id: '/api/attendance/qr'
      path: '/api/attendance/qr'
      fullPath: '/api/attendance/qr'
      preLoaderRoute: typeof ApiAttendanceQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/exams/$id/session': {
      id: '/student/exams/$id/session'
      path: '/exams/$id/session'
      fullPath: '/student/exams/$id/session'
      preLoaderRoute: typeof StudentExamsIdSessionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exams/$id/checkin': {
      id: '/student/exams/$id/checkin'
      path: '/exams/$id/checkin'
      fullPath: '/student/exams/$id/checkin'
      preLoaderRoute: typeof StudentExamsIdCheckinRouteImport
      parentRoute: typeof StudentRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exams/$examId/builder': {
      id: '/admin/exams/$examId/builder'
      path: '/$examId/builder'
      fullPath: '/admin/exams/$examId/builder'
      preLoaderRoute: typeof AdminExamsExamIdBuilderRouteImport
      parentRoute: typeof AdminExamsRoute
    }
  }
}

interface AdminExamsRouteChildren {
  AdminExamsExamIdBuilderRoute: typeof AdminExamsExamIdBuilderRoute
}

const AdminExamsRouteChildren: AdminExamsRouteChildren = {
  AdminExamsExamIdBuilderRoute: AdminExamsExamIdBuilderRoute,
}

const AdminExamsRouteWithChildren = AdminExamsRoute._addFileChildren(
  AdminExamsRouteChildren,
)

interface AdminRouteChildren {
  AdminAcademicIntegrityRoute: typeof AdminAcademicIntegrityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminCommunicationRoute: typeof AdminCommunicationRoute
  AdminExamsRoute: typeof AdminExamsRouteWithChildren
  AdminLiveMonitorRoute: typeof AdminLiveMonitorRoute
  AdminOrganizationRoute: typeof AdminOrganizationRoute
  AdminQuestionBankRoute: typeof AdminQuestionBankRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSchedulerRoute: typeof AdminSchedulerRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminViolationsRoute: typeof AdminViolationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademicIntegrityRoute: AdminAcademicIntegrityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminCommunicationRoute: AdminCommunicationRoute,
  AdminExamsRoute: AdminExamsRouteWithChildren,
  AdminLiveMonitorRoute: AdminLiveMonitorRoute,
  AdminOrganizationRoute: AdminOrganizationRoute,
  AdminQuestionBankRoute: AdminQuestionBankRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSchedulerRoute: AdminSchedulerRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminViolationsRoute: AdminViolationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAnnouncementsRoute: typeof StudentAnnouncementsRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentPaymentsRoute: typeof StudentPaymentsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentResultsRoute: typeof StudentResultsRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentExamsIdCheckinRoute: typeof StudentExamsIdCheckinRoute
  StudentExamsIdSessionRoute: typeof StudentExamsIdSessionRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAnnouncementsRoute: StudentAnnouncementsRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentPaymentsRoute: StudentPaymentsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentResultsRoute: StudentResultsRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentExamsIdCheckinRoute: StudentExamsIdCheckinRoute,
  StudentExamsIdSessionRoute: StudentExamsIdSessionRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  NotFoundRoute: NotFoundRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
  StudentRoute: StudentRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiVersionRoute: ApiVersionRoute,
  VerifyCertNumberRoute: VerifyCertNumberRoute,
  ApiAttendanceQrRoute: ApiAttendanceQrRoute,
  ApiCertificatesVerifyRoute: ApiCertificatesVerifyRoute,
  ApiResultsExportRoute: ApiResultsExportRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
